name: Archive Old Articles

on:
  schedule:
    # Runs every day at 1 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  archive-old-articles:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run archival script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python ArticleUpdates/archive_old_articles.py
          
      - name: Log completion
        run: echo "Article archival process completed"
