name: News Roundup Processor
on:
  schedule:
    - cron: '*/11 * * * *'  # Runs every 11 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-news-roundups:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      Custom_Search_API_KEY: ${{ secrets.CUSTOM_SEARCH_API_KEY }}
      GOOGLE_CUSTOM_SEARCH_ID: ${{ secrets.GOOGLE_CUSTOM_SEARCH_ID }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news roundup processor
      run: python news_roundup_processor.py