name: Personal Summary Generation

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-personal-summaries:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate personalized summaries
      run: python personal_summary_generator.py
      
    - name: Log completion
      run: |
        echo "Personal summary generation completed at $(date)"
        echo "Check logs above for detailed statistics"
